[package]
name = "wot-serve"
version = "0.1.0"
edition = "2021"
description = "Web of Things (WoT) Thing server"
license = "MIT"
repository = "https://github.com/sifis-home/wot-serve"
keywords = ["wot", "WebofThings"]

[dependencies]
